
def configure(installer):
    installer.name = 'venv'
    #
    # Add repositories
    #
    installer.add_repository('virtualenv', pypi='virtualenv')
    installer.add_repository('nose', pypi='nose')
    #
    # Define the contents of the README.txt file
    #
    installer.README="""
#
# Installation generated by the venv_install script.
#
# This directory is managed with virtualenv, which creates a
# virtual Python installation.  If the 'bin' directory is put in
# user's PATH environment, then the bin/python command can be used to
# employ SPOT without further installation.
#
# Directories:
#   admin      Administrative data for maintaining this distribution
#   bin        Scripts and executables
#   dist       Python packages that are not intended for development
#   include    Python header files
#   lib        Python libraries and installed packages
#   src        Python packages whose source files can be
#              modified and used directly within this virtual Python
#              installation.
#   Scripts    Python bin directory (used on MS Windows)
#
""" 
    #
    # Return the modified installer
    #
    return installer

