#!/bin/sh

if [ 1 ]; then
    # Install wheel if it's not already available
    pip install wheel

    # Clone virtualenv git repo
    rm -Rf virtualenv_git
    git clone https://github.com/pypa/virtualenv.git virtualenv_git

    # Create a wheel file for virtualenv
    pip wheel --wheel-dir virtualenv_git/virtualenv_support virtualenv

    # Move virtualenv_support into ../pyutilib/virtualenv
    rm -Rf ./virtualenv_support
    mv virtualenv_git/virtualenv_support .
fi

# Create a zipfile with the wheel files
zip -r virtualenv_support.zip virtualenv_support

# Fill the template with the ZIP file
python `dirname $0`/rebuild.py wheels_template.py wheels.py
cp wheels.py ../pyutilib/virtualenv

# Generate ../pyutilib/virtualenv/vpy_install.py
python update.py
